version: "3.7"

services:
  studio-react: 
    container_name: studio
    build: ./studio
    volumes:
      - "./studio:/app"
      - "./studio/app/node_modules"
    ports:
      - 8000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
