kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAME_SPACE}
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: ${SERVICE_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      name: ${SERVICE_NAME}
      labels:
        service: ${SERVICE_NAME}
    spec:
      containers:
      - name: ${SERVICE_NAME}
        image: gcr.io/airasia-bee-ppd/bee-airasia-medical-tourism:ppd-$CI_COMMIT_SHA
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: DD_ENV
          value: prod
        - name: DD_TRACE_ANALYTICS_ENABLED
          value: "true"
        - name: DD_TAGS
          value: "env:prod"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 200m
        ports:
        - name: http
          containerPort: ${CONTAINER_PORT}
        livenessProbe:
          httpGet:
            path: /health/healthz
            port: ${CONTAINER_PORT}
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/healthz
            port: ${CONTAINER_PORT}
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAME_SPACE}
  labels:
    service: ${SERVICE_NAME}
spec:
  ports:
  - name: http
    targetPort: ${CONTAINER_PORT}
    port: 80
  selector:
    service: ${SERVICE_NAME}
