kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${SERVICE_NAME}
  namespace: application
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      name: ${SERVICE_NAME}
      labels:
        service: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$SERVICE_NAME:$ENVIRONMENT-$CIRCLE_SHA1
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
            - name: AUTH_API
              value: 'http://cpos-microservice-management-auth'
            - name: SYSTEM_API
              value: 'http://cpos-microservice-management-system'
            - name: STORE_API
              value: 'http://cpos-microservice-management-store'
            - name: MENU_API
              value: 'http://cpos-microservice-management-menu'
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: URI
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: URI
          resources:
            requests:
              memory: '100Mi'
              cpu: '50m'
            limits:
              memory: '200Mi'
              cpu: '100m'
          ports:
            - name: http
              containerPort: 9050
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/src/app/healthcheck.html
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/src/app/healthcheck.html
            initialDelaySeconds: 60
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: application
  labels:
    service: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      targetPort: 9050
      port: 80
  selector:
    service: ${SERVICE_NAME}
